### ISSUE TITLE
关于我是404

### ISSUE THREAD

**Issue by code2828** [zxp2019/zxp2019.github.io#1]
关于我：我是谁，......
点进去以后是404啊！
###### zxp ak ioi ######

**Comment by zxp2019** [comment]
谔谔，好吧，现在才看见，你说的是哪一个页面呢

**Comment by zxp2019** [comment]
需要具体的页面信息

**Comment by zxp2019** [comment]
emmm，老版页面这类 bug 挺多的，可能来不及一一改了

**Comment by zxp2019** [comment]
em，实测首页和blog 页面都不是 404 啊

**Comment by code2828** [comment]
你居然理我了。。。我还以为你不理我呢。。。
