### ISSUE TITLE
Bug Report: 【今天去哪儿】板块图片显示问题

### ISSUE THREAD

**Issue by zxp2019** [zxp2019/zxp2019.github.io#34]
在不同的屏幕宽度下，【今天去哪儿】板块图片可能会溢出边界，如下图。

![图片](https://user-images.githubusercontent.com/62792133/91023155-c7007e00-e628-11ea-964c-e10dce21bb91.png)

推测为 `.blog img` 的 `width` 属性设置引起的副作用。

**Comment by Grace2525** [comment]
换成rem如何？
